workflows:
  android-vault-x:
    name: Vault X - Ultra File Locker
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.vaultx.ultrafilelocker"
        GOOGLE_PLAY_TRACK: "internal"
      java: 17
      node: 16
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      
      - name: Get Flutter packages
        script: |
          echo "Android native project - skipping Flutter setup"
      
      - name: Build Android APK
        script: |
          cd $CM_BUILD_DIR
          ./gradlew assembleRelease
      
      - name: Build Android App Bundle
        script: |
          cd $CM_BUILD_DIR
          ./gradlew bundleRelease
      
      - name: Run unit tests
        script: |
          cd $CM_BUILD_DIR
          ./gradlew testReleaseUnitTest
        test_report: app/build/test-results/testReleaseUnitTest/TEST-*.xml
      
      - name: Run instrumented tests
        script: |
          cd $CM_BUILD_DIR
          ./gradlew connectedAndroidTest
        test_report: app/build/outputs/androidTest-results/connected/TEST-*.xml
    
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/mapping.txt
      - app/build/reports/lint-results-release.html
    
    publishing:
      email:
        recipients:
          - developer@vaultx.com
        notify:
          success: true
          failure: true